---
apiVersion: v1
kind: Service
metadata:
  name: project-service
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
  - port: 80
    targetPort: 80
    name: http
    nodePort: 30090

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2 
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: seyedehsanhosseini/sample-project:<VERSION>
          ports:
            - containerPort: 80

